// <auto-generated />
using LTMKarur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LTMKarur.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016192801_AddUOMToCountMaster")]
    partial class AddUOMToCountMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LTMKarur.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LTMKarur.Models.CountMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UOM")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CountMasters");
                });

            modelBuilder.Entity("LTMKarur.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Crimp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Dent")
                        .HasColumnType("numeric");

                    b.Property<string>("Design")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("EndsPerDent")
                        .HasColumnType("numeric");

                    b.Property<int>("EndsPerInch")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PicksPerInch")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ReadOnLoom")
                        .HasColumnType("numeric");

                    b.Property<string>("WarpCount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WarpEndsPerBeam")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WarpWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("WeftCount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("LTMKarur.Models.YarnPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("WarpCount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WarpPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("WeftCount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WeftPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("YarnPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
